<?php

return [
    'classifier_version' => '2026-04-14.1',
    'fallback_classification' => [
        'unknown' => 'neutral',
        'browser_without_context' => 'context_dependent',
    ],
    'browser_apps' => [
        'google chrome',
        'chrome',
        'microsoft edge',
        'edge',
        'mozilla firefox',
        'firefox',
        'brave',
        'opera',
        'safari',
        'vivaldi',
    ],
    'browser_title_patterns' => [
        '/\s*-\s*google chrome$/iu',
        '/\s*-\s*chrome$/iu',
        '/\s*-\s*microsoft edge$/iu',
        '/\s*-\s*mozilla firefox$/iu',
        '/\s*-\s*firefox$/iu',
        '/\s*-\s*brave$/iu',
        '/\s*-\s*opera$/iu',
        '/\s*-\s*safari$/iu',
        '/\s*-\s*vivaldi$/iu',
    ],
    'app_aliases' => [
        'vscode' => ['visual studio code', 'vs code', 'code.exe', 'vscode'],
        'terminal' => ['terminal', 'windows terminal', 'powershell', 'cmd', 'command prompt', 'git bash'],
        'figma' => ['figma'],
        'postman' => ['postman'],
        'dbeaver' => ['dbeaver'],
        'mysql workbench' => ['mysql workbench'],
        'slack' => ['slack'],
        'teams' => ['microsoft teams', 'teams'],
        'zoom' => ['zoom'],
        'notion' => ['notion'],
        'whatsapp' => ['whatsapp'],
        'telegram' => ['telegram'],
        'discord' => ['discord'],
        'chatgpt' => ['chatgpt'],
        'claude' => ['claude'],
        'gemini' => ['gemini'],
    ],
    'default_rules' => [
        ['name' => 'GitHub', 'target_type' => 'domain', 'match_mode' => 'exact', 'target_value' => 'github.com', 'classification' => 'productive', 'priority' => 300, 'reason' => 'Code hosting and review'],
        ['name' => 'GitLab', 'target_type' => 'domain', 'match_mode' => 'exact', 'target_value' => 'gitlab.com', 'classification' => 'productive', 'priority' => 300, 'reason' => 'Code hosting and review'],
        ['name' => 'Bitbucket', 'target_type' => 'domain', 'match_mode' => 'exact', 'target_value' => 'bitbucket.org', 'classification' => 'productive', 'priority' => 300, 'reason' => 'Code hosting and review'],
        ['name' => 'Jira', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'jira', 'classification' => 'productive', 'priority' => 280, 'reason' => 'Task and issue tracking'],
        ['name' => 'Confluence', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'confluence', 'classification' => 'productive', 'priority' => 280, 'reason' => 'Documentation workspace'],
        ['name' => 'Notion', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'notion', 'classification' => 'productive', 'priority' => 280, 'reason' => 'Documentation workspace'],
        ['name' => 'Slack', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'slack', 'classification' => 'productive', 'priority' => 260, 'reason' => 'Work communication'],
        ['name' => 'Teams', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'teams', 'classification' => 'productive', 'priority' => 260, 'reason' => 'Work communication'],
        ['name' => 'Zoom', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'zoom', 'classification' => 'productive', 'priority' => 260, 'reason' => 'Meetings and calls'],
        ['name' => 'VS Code', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'vscode', 'classification' => 'productive', 'priority' => 320, 'reason' => 'Software development environment'],
        ['name' => 'Terminal', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'terminal', 'classification' => 'productive', 'priority' => 320, 'reason' => 'Engineering and operations tooling'],
        ['name' => 'Postman', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'postman', 'classification' => 'productive', 'priority' => 260, 'reason' => 'API testing'],
        ['name' => 'Figma', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'figma', 'classification' => 'productive', 'priority' => 260, 'reason' => 'Design tooling'],
        ['name' => 'Google Docs', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'docs.google', 'classification' => 'productive', 'priority' => 250, 'reason' => 'Document editing'],
        ['name' => 'Google Sheets', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'sheets.google', 'classification' => 'productive', 'priority' => 250, 'reason' => 'Spreadsheet work'],
        ['name' => 'Google Drive', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'drive.google', 'classification' => 'productive', 'priority' => 250, 'reason' => 'File collaboration'],
        ['name' => 'Stack Overflow', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'stackoverflow.com', 'classification' => 'productive', 'priority' => 240, 'reason' => 'Technical research'],
        ['name' => 'MDN', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'developer.mozilla.org', 'classification' => 'productive', 'priority' => 240, 'reason' => 'Technical documentation'],
        ['name' => 'Microsoft Learn', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'learn.microsoft.com', 'classification' => 'productive', 'priority' => 240, 'reason' => 'Technical documentation'],
        ['name' => 'Trello', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'trello.com', 'classification' => 'productive', 'priority' => 220, 'reason' => 'Task management'],
        ['name' => 'Asana', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'asana.com', 'classification' => 'productive', 'priority' => 220, 'reason' => 'Task management'],
        ['name' => 'Linear', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'linear.app', 'classification' => 'productive', 'priority' => 220, 'reason' => 'Task management'],
        ['name' => 'ClickUp', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'clickup.com', 'classification' => 'productive', 'priority' => 220, 'reason' => 'Task management'],
        ['name' => 'Outlook', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'outlook', 'classification' => 'productive', 'priority' => 200, 'reason' => 'Work email'],
        ['name' => 'Gmail', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'mail.google', 'classification' => 'productive', 'priority' => 200, 'reason' => 'Work email'],
        ['name' => 'Google Calendar', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'calendar.google', 'classification' => 'productive', 'priority' => 200, 'reason' => 'Calendar and scheduling'],
        ['name' => 'ChatGPT', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'chatgpt', 'classification' => 'productive', 'priority' => 210, 'reason' => 'Work assistant tooling'],
        ['name' => 'Claude', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'claude', 'classification' => 'productive', 'priority' => 210, 'reason' => 'Work assistant tooling'],
        ['name' => 'Gemini', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'gemini', 'classification' => 'productive', 'priority' => 210, 'reason' => 'Work assistant tooling'],
        ['name' => 'YouTube', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'youtube.com', 'classification' => 'context_dependent', 'priority' => 210, 'reason' => 'Video can be training or entertainment depending on context'],
        ['name' => 'WhatsApp', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'whatsapp', 'classification' => 'context_dependent', 'priority' => 210, 'reason' => 'Messaging can be work or personal'],
        ['name' => 'Telegram', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'telegram', 'classification' => 'context_dependent', 'priority' => 210, 'reason' => 'Messaging can be work or personal'],
        ['name' => 'Discord', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'discord', 'classification' => 'context_dependent', 'priority' => 180, 'reason' => 'Chat server may or may not be work-related'],
        ['name' => 'Netflix', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'netflix.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Entertainment streaming'],
        ['name' => 'Instagram', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'instagram.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Social media entertainment'],
        ['name' => 'Facebook', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'facebook.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Social media entertainment'],
        ['name' => 'Twitter X', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'x.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Social media entertainment'],
        ['name' => 'Twitter', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'twitter.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Social media entertainment'],
        ['name' => 'Reddit', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'reddit.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Community browsing and entertainment'],
        ['name' => 'TikTok', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'tiktok.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Entertainment browsing'],
        ['name' => 'Twitch', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'twitch.tv', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Entertainment streaming'],
        ['name' => 'Pinterest', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'pinterest.com', 'classification' => 'unproductive', 'priority' => 280, 'reason' => 'General browsing and inspiration'],
        ['name' => 'Spotify', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'spotify.com', 'classification' => 'unproductive', 'priority' => 250, 'reason' => 'Music streaming'],
    ],
];
