<?php

return [
    'normalization' => [
        'merge_gap_seconds' => 5,
        'noise_threshold_seconds' => 2,
        'idle_threshold_seconds' => 60,
        'max_log_duration_seconds' => 14400,
    ],

    'cache' => [
        'ttl_seconds' => 300,
        'prefix' => 'usage-processing',
    ],

    'rules' => [
        'productive' => [
            'github.com',
            'gitlab.com',
            'stackoverflow.com',
            'stack overflow',
            'vscode',
            'visual studio code',
            'postman',
            'localhost',
            '127.0.0.1',
            'carevance',
            'jira',
            'confluence',
            'notion',
            'slack',
            'teams',
            'zoom',
            'outlook',
            'gmail',
            'docs.google',
            'chat.openai',
            'chatgpt',
        ],
        'unproductive' => [
            'instagram.com',
            'instagram',
            'facebook.com',
            'facebook',
            'youtube.com',
            'youtube',
            'web.whatsapp.com',
            'whatsapp',
            'reddit.com',
            'reddit',
            'spotify.com',
            'spotify',
            'netflix.com',
            'netflix',
        ],
        'neutral' => [
            'linkedin.com',
            'linkedin',
        ],
    ],

    'canonical_labels' => [
        'github.com' => ['github.com', 'github'],
        'gitlab.com' => ['gitlab.com', 'gitlab'],
        'stackoverflow.com' => ['stackoverflow.com', 'stack overflow', 'stackoverflow'],
        'linkedin.com' => ['linkedin.com', 'linkedin'],
        'instagram.com' => ['instagram.com', 'instagram'],
        'facebook.com' => ['facebook.com', 'facebook', 'fb.com'],
        'youtube.com' => ['youtube.com', 'youtu.be', 'youtube'],
        'web.whatsapp.com' => ['web.whatsapp.com', 'web.whatsapp', 'whatsapp', 'wa.me'],
        'reddit.com' => ['reddit.com', 'reddit'],
        'spotify.com' => ['spotify.com', 'spotify'],
        'netflix.com' => ['netflix.com', 'netflix'],
        'localhost' => ['localhost', '127.0.0.1'],
        'vscode' => ['visual studio code', 'vs code', 'vscode'],
        'postman' => ['postman'],
        'carevance' => ['carevance'],
        'jira' => ['jira'],
        'confluence' => ['confluence'],
        'notion' => ['notion'],
        'slack' => ['slack'],
        'teams' => ['microsoft teams', 'teams'],
        'zoom' => ['zoom'],
        'outlook' => ['outlook'],
        'gmail' => ['gmail'],
        'docs.google' => ['docs.google', 'google docs'],
        'chat.openai.com' => ['chat.openai', 'chatgpt'],
    ],
];
