<?php

return [
    'normalization' => [
        'merge_gap_seconds' => 5,
        'noise_threshold_seconds' => 2,
        'idle_threshold_seconds' => 60,
        'max_log_duration_seconds' => 14400,
    ],

    'cache' => [
        'ttl_seconds' => 300,
        'prefix' => 'usage-processing',
    ],

    'rules' => [
        'productive' => [
            'github.com',
            'gitlab.com',
            'bitbucket.org',
            'bitbucket',
            'stackoverflow.com',
            'stack overflow',
            'vscode',
            'visual studio code',
            'postman',
            'localhost',
            '127.0.0.1',
            'carevance',
            'jira',
            'confluence',
            'notion',
            'slack',
            'teams',
            'zoom',
            'outlook',
            'gmail',
            'docs.google',
            'sheets.google',
            'drive.google',
            'meet.google',
            'calendar.google',
            'figma.com',
            'figma',
            'miro.com',
            'miro',
            'canva.com',
            'canva',
            'cursor',
            'code',
            'terminal',
            'powershell',
            'cmd',
            'intellij',
            'pycharm',
            'webstorm',
            'phpstorm',
            'android studio',
            'datagrip',
            'dbeaver',
            'tableplus',
            'mysql workbench',
            'navicat',
            'word',
            'excel',
            'powerpoint',
            'trello.com',
            'trello',
            'asana.com',
            'asana',
            'linear.app',
            'linear',
            'clickup.com',
            'clickup',
            'developer.mozilla.org',
            'developer.mozilla',
            'learn.microsoft.com',
            'learn.microsoft',
            'chat.openai',
            'chatgpt',
            'claude.ai',
            'gemini.google',
        ],
        'unproductive' => [
            'instagram.com',
            'instagram',
            'facebook.com',
            'facebook',
            'fb.com',
            'youtube.com',
            'youtube',
            'web.whatsapp.com',
            'whatsapp',
            'wa.me',
            'reddit.com',
            'reddit',
            'spotify.com',
            'spotify',
            'netflix.com',
            'netflix',
            'tiktok.com',
            'tiktok',
            'x.com',
            'twitter.com',
            'twitter',
            'discord.com',
            'discord',
            'twitch.tv',
            'twitch',
            'pinterest.com',
            'pinterest',
            'telegram.org',
            'telegram',
            'snapchat.com',
            'snapchat',
            'primevideo.com',
            'primevideo',
            'hotstar.com',
            'hotstar',
            '9gag.com',
            '9gag',
            'cricbuzz.com',
            'cricbuzz',
            'espncricinfo.com',
            'espncricinfo',
            'reels',
            'shorts',
        ],
        'neutral' => [
            'linkedin.com',
            'linkedin',
        ],
    ],

    'canonical_labels' => [
        'github.com' => ['github.com', 'github'],
        'gitlab.com' => ['gitlab.com', 'gitlab'],
        'bitbucket.org' => ['bitbucket.org', 'bitbucket'],
        'stackoverflow.com' => ['stackoverflow.com', 'stack overflow', 'stackoverflow'],
        'linkedin.com' => ['linkedin.com', 'linkedin'],
        'instagram.com' => ['instagram.com', 'instagram'],
        'facebook.com' => ['facebook.com', 'facebook', 'fb.com'],
        'youtube.com' => ['youtube.com', 'youtu.be', 'youtube'],
        'web.whatsapp.com' => ['web.whatsapp.com', 'web.whatsapp', 'whatsapp', 'wa.me'],
        'reddit.com' => ['reddit.com', 'reddit'],
        'spotify.com' => ['spotify.com', 'spotify'],
        'netflix.com' => ['netflix.com', 'netflix'],
        'localhost' => ['localhost', '127.0.0.1'],
        'vscode' => ['visual studio code', 'vs code', 'vscode'],
        'postman' => ['postman'],
        'carevance' => ['carevance'],
        'cursor' => ['cursor'],
        'terminal' => ['terminal'],
        'powershell' => ['powershell'],
        'cmd' => ['command prompt', 'cmd.exe', 'cmd'],
        'intellij' => ['intellij'],
        'pycharm' => ['pycharm'],
        'webstorm' => ['webstorm'],
        'phpstorm' => ['phpstorm'],
        'android studio' => ['android studio'],
        'datagrip' => ['datagrip'],
        'dbeaver' => ['dbeaver'],
        'tableplus' => ['tableplus'],
        'mysql workbench' => ['mysql workbench'],
        'navicat' => ['navicat'],
        'word' => ['microsoft word', 'word'],
        'excel' => ['microsoft excel', 'excel'],
        'powerpoint' => ['microsoft powerpoint', 'powerpoint'],
        'jira' => ['jira'],
        'confluence' => ['confluence'],
        'notion' => ['notion'],
        'slack' => ['slack'],
        'teams' => ['microsoft teams', 'teams'],
        'zoom' => ['zoom'],
        'outlook' => ['outlook'],
        'gmail' => ['gmail'],
        'docs.google' => ['docs.google', 'google docs'],
        'sheets.google' => ['sheets.google', 'google sheets'],
        'drive.google' => ['drive.google', 'google drive'],
        'meet.google' => ['meet.google', 'google meet'],
        'calendar.google' => ['calendar.google', 'google calendar'],
        'figma.com' => ['figma.com', 'figma'],
        'miro.com' => ['miro.com', 'miro'],
        'canva.com' => ['canva.com', 'canva'],
        'trello.com' => ['trello.com', 'trello'],
        'asana.com' => ['asana.com', 'asana'],
        'linear.app' => ['linear.app', 'linear'],
        'clickup.com' => ['clickup.com', 'clickup'],
        'developer.mozilla.org' => ['developer.mozilla.org', 'developer.mozilla'],
        'learn.microsoft.com' => ['learn.microsoft.com', 'learn.microsoft'],
        'chat.openai.com' => ['chat.openai', 'chatgpt'],
        'claude.ai' => ['claude.ai'],
        'gemini.google' => ['gemini.google'],
        'tiktok.com' => ['tiktok.com', 'tiktok'],
        'x.com' => ['x.com', 'twitter.com', 'twitter'],
        'discord.com' => ['discord.com', 'discord'],
        'twitch.tv' => ['twitch.tv', 'twitch'],
        'pinterest.com' => ['pinterest.com', 'pinterest'],
        'telegram.org' => ['telegram.org', 'telegram'],
        'snapchat.com' => ['snapchat.com', 'snapchat'],
        'primevideo.com' => ['primevideo.com', 'primevideo'],
        'hotstar.com' => ['hotstar.com', 'hotstar'],
        '9gag.com' => ['9gag.com', '9gag'],
        'cricbuzz.com' => ['cricbuzz.com', 'cricbuzz'],
        'espncricinfo.com' => ['espncricinfo.com', 'espncricinfo'],
    ],
];
